namespace GPS_Logger.Security.Messages
{
    /// <summary>
    /// A request message from a client to the server
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public class MessageFromClient<T>
    {
        /// <summary>
        /// The client's ID
        /// </summary>
        public string ID { get; set; }

        /// <summary>
        /// A random salt, generated by the client
        /// </summary>
        public string ClientSalt { get; set; }

        /// <summary>
        /// The client's time, in Unix time
        /// </summary>
        public long ClientEpoch { get; set; }

        /// <summary>
        /// The client's request payload
        /// </summary>
        public T Contents { get; set; }

        /// <summary>
        /// Hashed using the client's secret, which the server is able to verify by deriving the secret from the client's ID
        /// </summary>
        public string HMAC { get; set; }
    }
}